export const agentRules = {
  version: "stage-1-evolutionary-v2",
  cleaning: {
    noisyLabels: [
      // Navigation
      "home",
      "about",
      "contact",
      "login",
      "sign in",
      "sign up",
      "get started",
      "privacy policy",
      "terms",
      "terms of service",
      "terms and conditions",
      "cookie policy",
      "menu",
      "close menu",
      "open menu",
      "hamburger menu",
      "copyright",
      "all rights reserved",
      "read more",
      "learn more",
      "skip to content",
      "skip to main content",
      "back to top",
      "scroll to top",
      // Generic category headings (nav labels, not real offerings)
      "products",
      "services",
      "solutions",
      "features",
      "industries",
      "offerings",
      // CTAs
      "buy now",
      "shop now",
      "order now",
      "get a quote",
      "request a demo",
      "free trial",
      "start free",
      "try for free",
      "contact us",
      "talk to us",
      "reach out",
      "send message",
      "submit",
      // Common repeated fragments
      "view all",
      "see all",
      "load more",
      "show more",
      "next",
      "previous",
      "back",
      "search",
      // Auth / account
      "register",
      "create account",
      "forgot password",
    ],
    maxRepeatedLineCount: 2,
    minBusinessLineLength: 18,
  },
  crawler: {
    /** Maximum number of pages to crawl per website */
    maxPages: 60,
    /** Request timeout in milliseconds */
    timeoutMs: 15_000,
    /** Maximum response body size in bytes */
    maxBytes: 2_000_000,
  },
  identity: {
    titleSeparators: ["|", "-", "•", ":", "–", "—"],
  },
  industry: [
    // Manufacturing MUST come before Technology — "automation" in CNC/machine descriptions
    // would otherwise falsely match the Technology SaaS pattern
    { pattern: "manufacturing|factory|industrial|machining|ironworker|hydraulic|cnc|fabricat|casting|forging|metalwork|press|punching machine|shearing|welding|components|equipment", industry: "Manufacturing", subIndustry: "Industrial manufacturing", businessModel: "B2B manufacturing" },
    { pattern: "crm|erp|saas|workflow|automation|dashboard|analytics", industry: "Technology", subIndustry: "Business software", businessModel: "B2B SaaS" },
    { pattern: "\\bai\\b|machine learning|data science|computer vision|nlp|artificial intelligence", industry: "Technology", subIndustry: "Artificial intelligence", businessModel: "B2B software" },
    { pattern: "cybersecurity|infosec|firewall|penetration testing|soc|siem", industry: "Technology", subIndustry: "Cybersecurity", businessModel: "B2B software" },
    { pattern: "ecommerce|e-commerce|online store|shopify|marketplace|cart", industry: "Retail", subIndustry: "E-commerce", businessModel: "B2C / B2B commerce" },
    { pattern: "marketing|seo|brand|advertising|creative|content|digital agency|pr agency", industry: "Marketing", subIndustry: "Digital marketing services", businessModel: "B2B services" },
    { pattern: "logistics|supply chain|freight|shipping|courier|warehouse|3pl", industry: "Logistics", subIndustry: "Supply chain & logistics", businessModel: "B2B services" },
    { pattern: "clinic|medical|healthcare|wellness|therapy|dental|hospital|pharma|biotech", industry: "Healthcare", subIndustry: "Clinical or wellness services", businessModel: "B2C services" },
    { pattern: "course|training|school|academy|learning|education|edtech|lms", industry: "Education", subIndustry: "Training and education", businessModel: "B2C services" },
    { pattern: "real estate|property|homes|apartments|broker|realty|construction|architecture", industry: "Real Estate", subIndustry: "Property services", businessModel: "B2C services" },
    { pattern: "restaurant|cafe|food|menu|catering|hospitality|hotel|resort", industry: "Food and Beverage", subIndustry: "Hospitality", businessModel: "B2C services" },
    { pattern: "consulting|strategy|advisory|implementation|management consulting", industry: "Professional Services", subIndustry: "Business consulting", businessModel: "B2B services" },
    { pattern: "finance|fintech|banking|insurance|investment|accounting|wealth", industry: "Financial Services", subIndustry: "Finance and fintech", businessModel: "B2B / B2C services" },
    { pattern: "legal|law firm|attorney|solicitor|compliance|regulatory", industry: "Legal Services", subIndustry: "Legal advisory", businessModel: "B2B / B2C services" },
  ],
  offerings: {
    productNouns: [
      "platform", "software", "app", "application", "tool", "dashboard", "suite",
      "machine", "equipment", "device", "product", "system", "solution", "hardware",
      "kit", "component", "module", "engine", "robot", "printer", "scanner",
      "sensor", "controller", "pump", "valve", "conveyor", "packaging", "material",
    ],
    serviceNouns: [
      "service", "consulting", "implementation", "development", "design",
      "marketing", "support", "training", "audit", "management", "advisory",
      "integration", "deployment", "migration", "analytics", "research",
      "testing", "maintenance", "repair", "installation", "monitoring",
      "outsourcing", "staffing", "recruiting", "coaching", "therapy",
    ],
    valueClaimVerbs: [
      "help", "increase", "reduce", "automate", "improve", "grow", "protect",
      "simplify", "accelerate", "optimize", "save", "boost", "transform",
      "deliver", "enable", "empower", "streamline", "scale",
    ],
  },
  audience: {
    personas: {
      businesses: "Business decision makers",
      teams: "Operational teams",
      founders: "Founders and small business owners",
      enterprises: "Enterprise buyers",
      students: "Students and learners",
      patients: "Patients or wellness consumers",
      homeowners: "Homeowners",
      creators: "Creators",
      developers: "Developers",
      manufacturers: "Manufacturing and production managers",
    },
    targetIndustries: [
      "healthcare", "finance", "education", "retail", "manufacturing",
      "real estate", "technology", "hospitality", "logistics", "legal",
      "construction", "energy", "automotive",
    ],
  },
  brand: {
    tones: [
      { pattern: "enterprise|secure|compliance|scale|reliable|robust|certified", label: "Professional and enterprise-oriented" },
      { pattern: "creative|beautiful|story|design|brand|aesthetic|bold", label: "Creative and expressive" },
      { pattern: "easy|simple|friendly|support|helpful|intuitive|accessible", label: "Accessible and helpful" },
      { pattern: "innovative|cutting.edge|next.gen|future|disrupting|breakthrough", label: "Innovative and forward-looking" },
      { pattern: "affordable|cost-effective|value|budget|savings|cheap", label: "Value-driven" },
    ],
    uspPatterns: [
      "best", "leading", "trusted", "fast", "easy", "custom", "expert",
      "end-to-end", "certified", "proven", "award", "iso", "patented",
      "industry-leading", "world-class", "premium",
    ],
  },
  locations: [
    "United States", "USA", "India", "United Kingdom", "UAE",
    "Canada", "Australia", "Singapore", "Germany", "France",
    "Japan", "China", "Brazil", "South Africa", "Netherlands",
    "New York", "London", "Mumbai", "Delhi", "Bengaluru", "Bangalore",
    "Dubai", "San Francisco", "Los Angeles", "Chicago", "Toronto",
    "Sydney", "Melbourne", "Berlin", "Amsterdam", "Paris",
  ],
  qc: {
    maxNoiseRatio: 0.3,
    /** Minimum confidence score (0–1) required to pass QC without triggering re-run */
    minConfidenceScore: 0.85,
    requiredMemoryFields: [
      "businessIdentity",
      "industryClassification",
      "offerings",
      "audience",
      "brandPositioning",
      "digitalMaturity",
      "rdInsights",
    ],
  },
} as const;
